### ISSUE TITLE
Error trying to import to Android Studio

### ISSUE THREAD

**Issue by qamarq** [WMS-DEV/usos4j#17]
Hi, very good work regarding integration with USOS. But I have one question, what configuration do you recommend for Android Studio to make the library work? With import: `implementation(libs.usos4j)` (import from gradle kts, latest version 1.1.4) and java version:
```java
compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
}
```
an error occurs when trying to build: **Invalid build configuration. Attempt to create a global synthetic for 'Record desugaring' without a global-synthetics consumer.**

console:
```
* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform usos4j-1.1.4.jar (pl.wmsdev:usos4j:1.1.4) to match attributes {artifactType=android-dex, dexing-component-attributes=ComponentSpecificParameters(minSdkVersion=28, debuggable=true, enableCoreLibraryDesugaring=false, enableGlobalSynthetics=false, enableApiModeling=false, dependenciesClassesAreInstrumented=false, asmTransformComponent=null, useJacocoTransformInstrumentation=false, enableDesugaring=true, needsClasspath=false, useFullClasspath=false, componentIfUsingFullClasspath=null), org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingNoClasspathTransform: C:\Users\kamil\.gradle\caches\modules-2\files-2.1\pl.wmsdev\usos4j\1.1.4\e49313046c5a5543f72e14fb942b7ce733c0e79b\usos4j-1.1.4.jar.
         > Error while dexing.
```

**Comment by pszumanski** [comment]
Hi @qamarq!

Thank you for choosing usos4j and sharing your compile options. When it comes to configuration, Java 17 or higher is required for the library to function properly. Please, try upgrading your Java version and let us know if this resolves the issue.

Should you face any further issues, do not hesitate to contact us.

Best regards,
Piotr

**Comment by qamarq** [comment]
Hi @pszumanski 
I just figured this out. Its working I think from **JavaVersion.VERSION_14** (17 also) but more important is to add 
```
  packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
            excludes += "META-INF/INDEX.LIST"
            excludes += "META-INF/DEPENDENCIES"
        }
  } 
``` 

cause without this, will be errors. Thanks for help
Kamil
