### ISSUE TITLE
Missing get in timetable class

### ISSUE THREAD

**Issue by qamarq** [WMS-DEV/usos4j#20]
Hi Team,
Another question/bug. How can I get from activity (UsosTimeTableActivity) something else than defined gets like name or starttime. I need all info. How can I get vars I want, or u need add something like get() to get vars I want. Like groupNumber or roomNumber.

**Comment by qamarq** [comment]
Or maybe add to classes .toJava() or in toString function return simple json

**Comment by gniadeck** [comment]
hi, i think i might not understand your question fully - if you want to get start time or name, you can simply use getters that are provided in the library
```java
    @Generated
    public LocalDateTime getStartTime() {
        return this.startTime;
    }

    @Generated
    public LocalDateTime getEndTime() {
        return this.endTime;
    }

    @Generated
    public UsosLocalizedString getName() {
        return this.name;
    }
// decompiled code of UsosTimeTableActivity usos4j:1.1.5
```

i'm also not sure what do you mean by adding `.toJava()` method, but if you want to have full control over the request and return type mapping, you can use the generic endpoint
```java
var usos = Usos.builder()......build();
var serverApi = usos.getServerApi();
var usosApiRefModuleResponse = serverApi.generic()
                .request("services/apiref/module", Map.of("name", List.of("services/crstests")), UsosApiRefModule.class); // this is performed as an unauthenticated API client
var userApi = usos.getUserApi();
var userApiRefModuleResponse = userApi.generic()
                .request("services/apiref/module", Map.of("name", List.of("services/crstests")), UsosApiRefModule.class); // this is performed as a user
```
This way you can skip our mapping, or potentialy use some external library to map object returned from the library to JSON

**Comment by gniadeck** [comment]
hi, if I understand your question correctly, you mean that you would like to get additional information from the `UsosTimeTableActivity` based on the type of the activity. USOS API's docs defines [4 activity types](https://apps.usos.pw.edu.pl/developers/api/services/tt/#classgroup), and we should support all of them (classgroup and classgroup2 are merged together in our implementation in `UsosTimeTableClassGroupActivity`).

This means that if you query for example `.staff(_ , _)` method, you will get a list of `UsosTimeTableActivity`, that can possibly contain different types of `UsosTimeTableActivity` inside (like `UsosTimeTableClassGroupActivity, UsosTimeTableMeetingActivity, UsosTimeTableExamActivity`). Are you experiencing any problems with the deserialization (eg. you expected some activity to appear as an instance of subtype, but still apears as a `UsosTimeTableActivity`), or rather it was just an issue of getting more info about the subtypes of activities?
